export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';


export const CART_RESET_EMPTY = 'CART_RESET_EMPTY';

export const SEND_MAIL_ORDER_REQUEST = 'SEND_MAIL_ORDER_REQUEST';
export const SEND_MAIL_ORDER_SUCCESS = 'SEND_MAIL_ORDER_SUCCESS';
