export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_PAID_REQUEST = 'ORDER_PAID_REQUEST';
export const ORDER_PAID_SUCCESS = 'ORDER_PAID_SUCCESS';
export const ORDER_PAID_FAIL = 'ORDER_PAID_FAIL';

export const ORDER_MINE_LIST_REQUEST = 'ORDER_MINE_LIST_REQUEST';
export const ORDER_MINE_LIST_SUCCESS = 'ORDER_MINE_LIST_SUCCESS';
export const ORDER_MINE_LIST_FAIL = 'ORDER_MINE_LIST_FAIL';

export const ORDER_APPROVE_REQUEST = 'ORDER_APPROVE_REQUEST';
export const ORDER_APPROVE_SUCCESS = 'ORDER_APPROVE_SUCCESS';
export const ORDER_APPROVE_FAIL = 'ORDER_APPROVE_FAIL';