export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_CONFIRM_EMAIL_REQUEST = 'USER_CONFIRM_EMAIL_REQUEST';
export const USER_CONFIRM_EMAIL_SUCCESS = 'USER_CONFIRM_EMAIL_SUCCESS';
export const USER_CONFIRM_EMAIL_FAIL = 'USER_CONFIRM_EMAIL_FAIL';

export const USER_FOGOT_PASSWORD_REQUEST = 'USER_FOGOT_PASSWORD_REQUEST';
export const USER_FOGOT_PASSWORD_SUCCESS = 'USER_FOGOT_PASSWORD_SUCCESS';
export const USER_FOGOT_PASSWORD_FAIL = 'USER_FOGOT_PASSWORD_FAIL';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';

export const USER_ENTER_CODE_RESET_PASSWORD_REQUEST = 'USER_ENTER_CODE_RESET_PASSWORD_REQUEST';
export const USER_ENTER_CODE_RESET_PASSWORD_SUCCESS = 'USER_ENTER_CODE_RESET_PASSWORD_SUCCESS';
export const USER_ENTER_CODE_RESET_PASSWORD_FAIL = 'USER_ENTER_CODE_RESET_PASSWORD_FAIL';
